services:  
  mobile_app: 
    container_name: mobile_app  # optional
    build:
      context: . 
      dockerfile: Dockerfile  # optional, default is Dockerfile in context
    ports:
      - 19000:19000 
      - 19001:19001
      - 19002:19002
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # - CHOKIDAR_USEPOLLING=true # Drains batterty, to be checked without usage, used for hot reload
      - REACT_NATIVE_PACKAGER_HOSTNAME=172.20.10.2 # TODO: USE YOUR IPV4 address without any port
      - MONGODB_CONNSTRING=mongodb://root:secret@mongodb # (experimental)
    volumes:
      - type: volume
        source: sih_mobile_app
        target: /root/app/
        volume:
          nocopy: true
      # - code:/root/workspace/app # TODO: change to your workspace
  auth_server:
    container_name: auth_server
    build:
      context: .
      dockerfile: Dockerfile.auth_server
    ports:
      - 1111:1111
    volumes:
      - type: volume
        source: sih_server_auth
        target: /root/servers/auth
        volume:
          nocopy: true
      # - code:/root/workspace/servers/auth
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=db
    volumes:
      - "C:\\Users\\Public\\db:/data/db" # mount is in the local machine
volumes:
  sih_mobile_app:
    name: sih_mobile_app
  sih_server_auth:
    name: sih_server_auth